### ISSUE TITLE
Mirroring directories on same server (Docker)

### ISSUE THREAD

**Issue by EZarnosky** [stephenh/mirror#67]
I am trying to mirror a user folder to a shared folder on my docker host, but have been unsuccessful. Is this possible? If so what could be wrong with my compose file below?

Another question regarding increasing **fs.inotify.max_user_watches** & **fs.inotify.max_queued_events**, is this done in the docker container or the docker host?

```
version: "3.0"

services:
  mirror:
    image: quay.io/stephenh/mirror
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/docker/folder:/data
      - /home/dockeruser:/data-local
    command:
      - --local-root /data
      - --remote-root /data-local
```
